-- MySQL Script generated by MySQL Workbench
-- Sun 07 May 2017 10:28:42 PM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DiscordBot
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DiscordBot` ;

-- -----------------------------------------------------
-- Schema DiscordBot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DiscordBot` DEFAULT CHARACTER SET utf8 ;
USE `DiscordBot` ;

-- -----------------------------------------------------
-- Table `DiscordBot`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DiscordBot`.`users` ;

CREATE TABLE IF NOT EXISTS `DiscordBot`.`users` (
  `id` BIGINT NOT NULL,
  `xp` INT NULL,
  `rights_lvl` INT NOT NULL,
  `username` VARCHAR(256) NOT NULL,
  `nickname` VARCHAR(256) NOT NULL,
  `botHistory` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
