-- MySQL Script generated by MySQL Workbench
-- Sat 20 May 2017 02:09:48 PM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DiscordBot
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DiscordBot` ;

-- -----------------------------------------------------
-- Schema DiscordBot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DiscordBot` DEFAULT CHARACTER SET utf8 ;
USE `DiscordBot` ;

-- -----------------------------------------------------
-- Table `DiscordBot`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DiscordBot`.`user` ;

CREATE TABLE IF NOT EXISTS `DiscordBot`.`user` (
  `id` CHAR(18) NOT NULL,
  `xp` INT NOT NULL DEFAULT 0,
  `lvl` INT NOT NULL DEFAULT 0,
  `username` VARCHAR(256) NOT NULL,
  `botHistory` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DiscordBot`.`server`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DiscordBot`.`server` ;

CREATE TABLE IF NOT EXISTS `DiscordBot`.`server` (
  `id` CHAR(18) NOT NULL,
  `name` VARCHAR(256) NOT NULL,
  `lvl_multiplier` DOUBLE NOT NULL DEFAULT 1.0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
PACK_KEYS = DEFAULT;


-- -----------------------------------------------------
-- Table `DiscordBot`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DiscordBot`.`role` ;

CREATE TABLE IF NOT EXISTS `DiscordBot`.`role` (
  `id` CHAR(18) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lvl` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DiscordBot`.`server_has_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DiscordBot`.`server_has_role` ;

CREATE TABLE IF NOT EXISTS `DiscordBot`.`server_has_role` (
  `server_id` CHAR(18) NOT NULL,
  `role_id` CHAR(18) NOT NULL,
  PRIMARY KEY (`server_id`, `role_id`),
  INDEX `fk_server_has_role_role1_idx` (`role_id` ASC),
  INDEX `fk_server_has_role_server1_idx` (`server_id` ASC),
  CONSTRAINT `fk_server_has_role_server1`
    FOREIGN KEY (`server_id`)
    REFERENCES `DiscordBot`.`server` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_server_has_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `DiscordBot`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DiscordBot`.`server_has_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DiscordBot`.`server_has_user` ;

CREATE TABLE IF NOT EXISTS `DiscordBot`.`server_has_user` (
  `server_id` CHAR(18) NOT NULL,
  `user_id` CHAR(18) NOT NULL,
  PRIMARY KEY (`server_id`, `user_id`),
  INDEX `fk_server_has_user_user1_idx` (`user_id` ASC),
  INDEX `fk_server_has_user_server1_idx` (`server_id` ASC),
  CONSTRAINT `fk_server_has_user_server1`
    FOREIGN KEY (`server_id`)
    REFERENCES `DiscordBot`.`server` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_server_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `DiscordBot`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
